version: "3.9"
services:
  # hardhat:
  #   build:
  #     context: .
  #     target: hardhat
  #   ports:
  #     - "8545:8545"
  #   volumes:
  #     - shared:/home/node/react-app/src/contracts
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8545" ]

  # hardhat_deploy:
  #   build:
  #     context: .
  #     target: hardhat
  #   command: ["yarn", "deploy"]
  #   depends_on:
  #     hardhat:
  #       condition: service_healthy
  #   environment:
  #     LOCALHOST_RPC_URL: "http://hardhat:8545"
  #   volumes:
  #     - shared:/home/node/react-app/src/contracts
  #   links:
  #     - hardhat
  #   healthcheck:
  #     test: [ "CMD", "ls", "/home/node/react-app/src/contracts/hardhat_contracts.json" ]
  react-app:
    image: "ghcr.io/buidlguidl/scaffold-eth:sha-7f7803d"
#    build:
#      context: .
    environment:
      BROWSER: none
    command: /bin/sh -c "while sleep 1000; do :; done"
    # depends_on:
    #   hardhat_deploy:
    #     condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - shared:/home/node/react-app/src/contracts

volumes:
  shared: