name: Create and publish Docker images

on:
  push:
    branches:
      - master
      - playground

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Metadata: react-app"
        id: meta_react_app
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-react-app
          tags: |
            type=sha
      - name: "Build and push: react-app"
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: false
          target: react-app
          tags: "${{ steps.meta_react_app.outputs.tags }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: "Metadata: hardhat"
        id: meta_hardhat
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-hardhat
          tags: |
            type=sha
      - name: "Build and push: hardhat"
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: false
          target: hardhat
          tags: "${{ steps.meta_hardhat.outputs.tags }}"



